
import { auth } from './firebase';
import { signInWithCustomToken } from 'firebase/auth';
import * as cookie from 'cookie';

export const handleSSOLogin = async (): Promise<void> => {
  const cookies = cookie.parse(document.cookie);
  const ssoToken = cookies.sso_token;

  if (ssoToken) {
    try {
      // The sso_token is a custom token generated by the api-server
      await signInWithCustomToken(auth, ssoToken);
    } catch (error) {
      console.error('Error signing in with SSO token:', error);
    }
  }
};
