#!/usr/bin/env python3
"""
AltaMedica Package Automation Setup
==================================

Script para configurar automatización de estandarización de package.json
en el monorepo AltaMedica.

Autor: Eduardo Altamedica
Versión: 1.0.0
"""

import os
import json
import logging
from pathlib import Path
from typing import Dict, Any
import subprocess
import time
from datetime import datetime

logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')
logger = logging.getLogger(__name__)

class PackageAutomationSetup:
    """Configurador de automatización para package.json"""
    
    def __init__(self, root_dir: str = "."):
        self.root_dir = Path(root_dir).resolve()
        self.hooks_dir = self.root_dir / ".git" / "hooks"
        self.scripts_dir = self.root_dir / "scripts" / "package-automation"
        
    def create_git_hooks(self):
        """Crea hooks de Git para estandarización automática"""
        if not self.hooks_dir.exists():
            logger.warning("⚠️  Directorio .git/hooks no encontrado. ¿Es un repositorio Git?")
            return False
        
        # Pre-commit hook para validación
        pre_commit_content = f'''#!/bin/sh
# AltaMedica Package.json Pre-commit Hook
# Auto-generated by setup-package-automation.py

echo "🔍 Validando package.json antes del commit..."

# Cambiar al directorio del proyecto
cd "{self.root_dir}"

# Ejecutar validación en modo silencioso
python3 standardize-packages.py --validate --quiet

if [ $? -ne 0 ]; then
    echo "❌ Error: package.json no está estandarizado"
    echo "💡 Ejecuta: python3 standardize-packages.py --dry-run"
    echo "💡 Luego: python3 standardize-packages.py"
    exit 1
fi

echo "✅ Package.json validado correctamente"
'''
        
        # Post-merge hook para auto-estandarización
        post_merge_content = f'''#!/bin/sh
# AltaMedica Package.json Post-merge Hook
# Auto-generated by setup-package-automation.py

echo "🔄 Ejecutando auto-estandarización post-merge..."

# Cambiar al directorio del proyecto
cd "{self.root_dir}"

# Solo estandarizar si hay cambios en package.json
if git diff-tree --name-only HEAD@{{1}} HEAD | grep -E "package\\.json$" > /dev/null; then
    echo "📦 Detectados cambios en package.json, estandarizando..."
    python3 standardize-packages.py --mode=auto --quiet
    
    if [ $? -eq 0 ]; then
        echo "✅ Estandarización automática completada"
    else
        echo "⚠️  Advertencia: Error en estandarización automática"
    fi
else
    echo "ℹ️  No hay cambios en package.json"
fi
'''
        
        try:
            # Crear pre-commit hook
            pre_commit_hook = self.hooks_dir / "pre-commit"
            with open(pre_commit_hook, 'w', encoding='utf-8') as f:
                f.write(pre_commit_content)
            pre_commit_hook.chmod(0o755)
            logger.info(f"✅ Pre-commit hook creado: {pre_commit_hook}")
            
            # Crear post-merge hook
            post_merge_hook = self.hooks_dir / "post-merge"
            with open(post_merge_hook, 'w', encoding='utf-8') as f:
                f.write(post_merge_content)
            post_merge_hook.chmod(0o755)
            logger.info(f"✅ Post-merge hook creado: {post_merge_hook}")
            
            return True
            
        except Exception as e:
            logger.error(f"❌ Error creando git hooks: {e}")
            return False
    
    def create_npm_scripts(self):
        """Agrega scripts NPM para estandarización"""
        root_package = self.root_dir / "package.json"
        
        try:
            with open(root_package, 'r', encoding='utf-8') as f:
                package_data = json.load(f)
            
            # Scripts de estandarización
            new_scripts = {
                "standardize": "python3 standardize-packages.py",
                "standardize:dry": "python3 standardize-packages.py --dry-run",
                "standardize:validate": "python3 standardize-packages.py --validate",
                "standardize:apps": "python3 standardize-packages.py --apps",
                "standardize:auto": "python3 standardize-packages.py --mode=auto --quiet",
                "hooks:install": "python3 setup-package-automation.py --install-hooks",
                "workspace:check": "python3 standardize-packages.py --validate && echo '✅ Workspace está estandarizado'"
            }
            
            existing_scripts = package_data.get("scripts", {})
            updated = False
            
            for script_name, script_command in new_scripts.items():
                if script_name not in existing_scripts:
                    existing_scripts[script_name] = script_command
                    updated = True
                    logger.info(f"➕ Script agregado: {script_name}")
            
            if updated:
                package_data["scripts"] = dict(sorted(existing_scripts.items()))
                
                with open(root_package, 'w', encoding='utf-8') as f:
                    json.dump(package_data, f, indent=2, ensure_ascii=False)
                
                logger.info("✅ Scripts NPM agregados al package.json raíz")
                return True
            else:
                logger.info("ℹ️  Scripts NPM ya están presentes")
                return True
                
        except Exception as e:
            logger.error(f"❌ Error agregando scripts NPM: {e}")
            return False
    
    def create_vscode_tasks(self):
        """Crea tareas de VS Code para estandarización"""
        vscode_dir = self.root_dir / ".vscode"
        vscode_dir.mkdir(exist_ok=True)
        
        tasks_file = vscode_dir / "tasks.json"
        
        tasks_config = {
            "version": "2.0.0",
            "tasks": [
                {
                    "label": "🔧 Estandarizar Package.json",
                    "type": "shell",
                    "command": "python3",
                    "args": ["standardize-packages.py"],
                    "group": "build",
                    "presentation": {
                        "echo": True,
                        "reveal": "always",
                        "focus": False,
                        "panel": "shared"
                    },
                    "problemMatcher": []
                },
                {
                    "label": "🎯 Validar Package.json (Dry Run)",
                    "type": "shell",
                    "command": "python3",
                    "args": ["standardize-packages.py", "--dry-run"],
                    "group": "test",
                    "presentation": {
                        "echo": True,
                        "reveal": "always",
                        "focus": False,
                        "panel": "shared"
                    },
                    "problemMatcher": []
                },
                {
                    "label": "✅ Validar Configuración",
                    "type": "shell",
                    "command": "python3",
                    "args": ["standardize-packages.py", "--validate"],
                    "group": "test",
                    "presentation": {
                        "echo": True,
                        "reveal": "always",
                        "focus": false,
                        "panel": "shared"
                    },
                    "problemMatcher": []
                }
            ]
        }
        
        try:
            with open(tasks_file, 'w', encoding='utf-8') as f:
                json.dump(tasks_config, f, indent=2, ensure_ascii=False)
            
            logger.info(f"✅ Tareas VS Code creadas: {tasks_file}")
            return True
            
        except Exception as e:
            logger.error(f"❌ Error creando tareas VS Code: {e}")
            return False
    
    def create_watcher_script(self):
        """Crea script watcher para monitoreo automático"""
        self.scripts_dir.mkdir(parents=True, exist_ok=True)
        
        watcher_script = self.scripts_dir / "package-watcher.py"
        
        watcher_content = f'''#!/usr/bin/env python3
"""
AltaMedica Package Watcher
=========================

Watcher automático para cambios en package.json
"""

import time
import os
import subprocess
from pathlib import Path
from watchdog.observers import Observer
from watchdog.events import FileSystemEventHandler
import logging

logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(message)s')
logger = logging.getLogger(__name__)

class PackageJsonHandler(FileSystemEventHandler):
    """Handler para cambios en package.json"""
    
    def __init__(self, root_dir):
        self.root_dir = Path(root_dir)
        self.last_processed = {{}}
        
    def on_modified(self, event):
        if not event.is_directory and event.src_path.endswith('package.json'):
            file_path = Path(event.src_path)
            
            # Evitar procesamiento duplicado
            current_time = time.time()
            if file_path in self.last_processed:
                if current_time - self.last_processed[file_path] < 2:  # 2 segundos cooldown
                    return
            
            self.last_processed[file_path] = current_time
            
            logger.info(f"📦 Detectado cambio en: {{file_path.relative_to(self.root_dir)}}")
            
            # Ejecutar estandarización automática
            try:
                result = subprocess.run([
                    'python3', 'standardize-packages.py', 
                    '--mode=auto', '--quiet'
                ], cwd=self.root_dir, capture_output=True, text=True)
                
                if result.returncode == 0:
                    logger.info("✅ Auto-estandarización completada")
                else:
                    logger.warning(f"⚠️  Error en auto-estandarización: {{result.stderr}}")
                    
            except Exception as e:
                logger.error(f"❌ Error ejecutando estandarización: {{e}}")

def main():
    root_dir = Path("{self.root_dir}")
    
    logger.info("🔍 Iniciando watcher de package.json para AltaMedica...")
    logger.info(f"📂 Monitoreando: {{root_dir}}")
    
    event_handler = PackageJsonHandler(root_dir)
    observer = Observer()
    
    # Monitorear apps/
    apps_dir = root_dir / "apps"
    if apps_dir.exists():
        observer.schedule(event_handler, str(apps_dir), recursive=True)
        logger.info(f"👀 Monitoreando: {{apps_dir}}")
    
    # Monitorear packages/
    packages_dir = root_dir / "packages"
    if packages_dir.exists():
        observer.schedule(event_handler, str(packages_dir), recursive=True)
        logger.info(f"👀 Monitoreando: {{packages_dir}}")
    
    # Monitorear agents/
    agents_dir = root_dir / "agents"
    if agents_dir.exists():
        observer.schedule(event_handler, str(agents_dir), recursive=True)
        logger.info(f"👀 Monitoreando: {{agents_dir}}")
    
    # Monitorear root
    observer.schedule(event_handler, str(root_dir), recursive=False)
    
    observer.start()
    logger.info("🚀 Watcher iniciado. Presiona Ctrl+C para detener.")
    
    try:
        while True:
            time.sleep(1)
    except KeyboardInterrupt:
        observer.stop()
        logger.info("⏹️  Watcher detenido")
    
    observer.join()

if __name__ == "__main__":
    main()
'''
        
        try:
            with open(watcher_script, 'w', encoding='utf-8') as f:
                f.write(watcher_content)
            watcher_script.chmod(0o755)
            
            logger.info(f"✅ Script watcher creado: {watcher_script}")
            
            # Crear requirements para el watcher
            requirements_file = self.scripts_dir / "requirements.txt"
            with open(requirements_file, 'w') as f:
                f.write("watchdog>=3.0.0\\n")
            
            logger.info(f"✅ Requirements creado: {requirements_file}")
            return True
            
        except Exception as e:
            logger.error(f"❌ Error creando watcher: {e}")
            return False
    
    def create_automation_readme(self):
        """Crea documentación del sistema de automatización"""
        readme_content = f'''# 🔧 Sistema de Automatización de Package.json

## 🎯 Propósito

Este sistema mantiene automáticamente la consistencia de todos los `package.json` en el monorepo AltaMedica.

## 🚀 Comandos Disponibles

### Scripts NPM (desde la raíz)
```bash
# Estandarizar todos los package.json
npm run standardize

# Vista previa de cambios (sin modificar archivos)
npm run standardize:dry

# Validar configuración
npm run standardize:validate

# Estandarizar apps específicas
npm run standardize:apps web-app doctors

# Estandarización automática (silenciosa)
npm run standardize:auto

# Verificar estado del workspace
npm run workspace:check
```

### Comandos Python Directos
```bash
# Estandarización completa
python3 standardize-packages.py

# Solo vista previa
python3 standardize-packages.py --dry-run

# Apps específicas
python3 standardize-packages.py --apps web-app api-server

# Validar configuración
python3 standardize-packages.py --validate

# Crear hooks de Git
python3 standardize-packages.py --create-hook
```

## 🔄 Automatización

### Git Hooks Instalados
- **Pre-commit**: Valida package.json antes de cada commit
- **Post-merge**: Auto-estandariza después de merge/pull

### VS Code Tasks
- `Ctrl+Shift+P` → "Tasks: Run Task"
- "🔧 Estandarizar Package.json"
- "🎯 Validar Package.json (Dry Run)"
- "✅ Validar Configuración"

### Watcher Automático
```bash
# Instalar dependencias del watcher
pip install -r scripts/package-automation/requirements.txt

# Iniciar watcher (monitoreo automático)
python3 scripts/package-automation/package-watcher.py
```

## 📋 Lo Que Se Estandariza

### ✅ Siempre Preservado (NO se modifica)
- `"type": "module"` - Configuración ES modules
- Dependencias existentes y sus versiones
- Scripts custom específicos de cada app
- Configuraciones funcionales

### 🔄 Opcionalmente Estandarizado
- Versiones de apps (`web-app`: "0.1.0", otros: "1.0.0")
- Formato de workspace dependencies (`workspace:*`)
- Scripts estándar faltantes
- Metadatos (author, license, keywords)

### 📦 Apps con Configuración Especial
- **web-app**: Mantiene versión "0.1.0" y scripts de testing
- **companies**: Preserva `server-fixed.js` y configuración HTTPS
- **admin**: Mantiene flag `--turbopack`
- **doctors**: Preserva scripts de signaling
- **api-server**: Mantiene build personalizado

## 🛠️ Configuración

### Archivo Principal
- `package-template-config.json` - Configuración maestra

### Estructura
```json
{{
  "templates": {{
    "app": {{ /* Template para aplicaciones */ }},
    "package": {{ /* Template para packages */ }}
  }},
  "appConfigurations": {{
    "web-app": {{ /* Config específica */ }}
  }},
  "optionalStandardizations": {{
    "preserveCustomConfigurations": true
  }}
}}
```

## 🔍 Troubleshooting

### Si los hooks no funcionan:
```bash
chmod +x .git/hooks/pre-commit
chmod +x .git/hooks/post-merge
```

### Si hay errores de ES modules:
- ✅ **No te preocupes**: El sistema preserva `"type": "module"`
- ✅ **Configuración actual está correcta**

### Para deshabilitar validación temporal:
```bash
git commit --no-verify -m "mensaje"
```

## 📊 Logs

- `package-standardization.log` - Log detallado de operaciones
- Backups automáticos en `backups/packages_YYYYMMDD_HHMMSS/`

---

*Sistema creado por Eduardo Altamedica para mantener consistencia en el monorepo.*
'''
        
        readme_file = self.root_dir / "PACKAGE_AUTOMATION_README.md"
        
        try:
            with open(readme_file, 'w', encoding='utf-8') as f:
                f.write(readme_content)
            
            logger.info(f"✅ Documentación creada: {readme_file}")
            return True
            
        except Exception as e:
            logger.error(f"❌ Error creando documentación: {e}")
            return False
    
    def install_all(self):
        """Instala todo el sistema de automatización"""
        logger.info("🚀 Instalando sistema de automatización AltaMedica...")
        
        success_count = 0
        total_steps = 5
        
        # 1. Git hooks
        if self.create_git_hooks():
            success_count += 1
        
        # 2. NPM scripts
        if self.create_npm_scripts():
            success_count += 1
        
        # 3. VS Code tasks
        if self.create_vscode_tasks():
            success_count += 1
        
        # 4. Watcher script
        if self.create_watcher_script():
            success_count += 1
        
        # 5. Documentación
        if self.create_automation_readme():
            success_count += 1
        
        # Resumen
        logger.info("=" * 60)
        logger.info("📊 RESUMEN DE INSTALACIÓN")
        logger.info("=" * 60)
        logger.info(f"✅ Componentes instalados: {success_count}/{total_steps}")
        
        if success_count == total_steps:
            logger.info("🎉 ¡Sistema de automatización instalado exitosamente!")
            logger.info("")
            logger.info("🔗 Próximos pasos:")
            logger.info("1. npm run standardize:validate  # Validar configuración")
            logger.info("2. npm run standardize:dry       # Vista previa de cambios")  
            logger.info("3. npm run standardize           # Aplicar estandarización")
            logger.info("")
            logger.info("📖 Ver PACKAGE_AUTOMATION_README.md para documentación completa")
            return True
        else:
            logger.warning(f"⚠️  Instalación parcial: {total_steps - success_count} errores")
            return False

def main():
    import argparse
    
    parser = argparse.ArgumentParser(description="Setup de automatización AltaMedica")
    parser.add_argument("--install-hooks", action="store_true", help="Solo instalar git hooks")
    parser.add_argument("--install-scripts", action="store_true", help="Solo instalar scripts NPM")
    parser.add_argument("--install-tasks", action="store_true", help="Solo instalar tareas VS Code")
    parser.add_argument("--install-watcher", action="store_true", help="Solo instalar watcher")
    parser.add_argument("--install-docs", action="store_true", help="Solo crear documentación")
    parser.add_argument("--install-all", action="store_true", default=True, help="Instalar todo")
    
    args = parser.parse_args()
    
    setup = PackageAutomationSetup()
    
    try:
        if args.install_hooks:
            return setup.create_git_hooks()
        elif args.install_scripts:
            return setup.create_npm_scripts()
        elif args.install_tasks:
            return setup.create_vscode_tasks()
        elif args.install_watcher:
            return setup.create_watcher_script()
        elif args.install_docs:
            return setup.create_automation_readme()
        else:
            return setup.install_all()
            
    except KeyboardInterrupt:
        logger.info("⏹️  Instalación cancelada por el usuario")
        return False
    except Exception as e:
        logger.error(f"❌ Error fatal: {e}")
        return False

if __name__ == "__main__":
    import sys
    success = main()
    sys.exit(0 if success else 1)